[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true

[tools]
# AI Agents
# "npm:@google/gemini-cli" = "latest"
# "npm:@anthropic-ai/claude-code" = "latest"
# "npm:@charmland/crush" = "latest"
# "npm:@openai/codex" = "latest"
# "npm:@github/copilot" = "latest"
"npm:opencode-ai" = "latest"

# Languages
node = "latest"
ko = "latest"
sops = "latest"
python = "latest"
pnpm = "latest"

# Develop tools
yq = "latest"
jq = "latest"
kubectl = "latest"
crane = "latest"
helm = "latest"
cmctl = "latest"
croc = "latest"
dive = "latest"
task = "latest"
lazygit = "latest"
gh = "latest"
